ToontownStart: Polling for game2 to finish...
ToontownStart: Game2 is finished.
ToontownStart: Starting the game.
ToontownStart: setting default font
TTLocalizer: Running in language: english
from toontown.toonbase.TTLocalizerEnglish import *
OTPLocalizer: Running in language: english
from otp.otpbase.OTPLocalizerEnglish import *
ToontownStart: Loading default gui sounds
ToontownStart: serverVersion:  tt2016-dev
Preloading avatars...
Done preloading avatars.
{401000001: <toontown.distributed.ToontownDistrict.ToontownDistrict instance at 0x134257B0>}
entering active SC menu
local
0
Reading DNA file... phase_4/dna/storage.dna
Reading DNA file... phase_3.5/dna/storage_interior.dna
Reading DNA file... phase_4/dna/storage_TT.dna
Reading DNA file... phase_4/dna/storage_TT_sz.dna
Reading DNA file... phase_4/dna/toontown_central_sz.dna
ignoring InputState-forward
Exception occurred while processing Func-hide-11 of Sequence-10:
Sequence-10:
  0.000 Sequence-10 {
  0.000   Wait dur 0.1
  0.100   Wait dur 6
  6.100   LerpColorScaleInterval-11: color_scale to 1 1 1 0 dur 0.5
  6.600   *Func-hide-11
  6.600 }

Traceback (most recent call last):
  File "C:\Panda3D-1.9.0\direct\showbase\ShowBase.py", line 1801, in __ivalLoop
    IntervalManager.ivalMgr.step()
  File "C:\Panda3D-1.9.0\direct\interval\IntervalManager.py", line 96, in step
    self.__doPythonCallbacks()
  File "C:\Panda3D-1.9.0\direct\interval\IntervalManager.py", line 119, in __doPythonCallbacks
    ival.privPostEvent()
  File "C:\Panda3D-1.9.0\direct\interval\MetaInterval.py", line 518, in privPostEvent
    self.__doPythonCallbacks()
  File "C:\Panda3D-1.9.0\direct\interval\MetaInterval.py", line 494, in __doPythonCallbacks
    ival.privDoEvent(t, eventType)
  File "C:\Panda3D-1.9.0\direct\interval\Interval.py", line 207, in privDoEvent
    self.privInstant()
  File "C:\Panda3D-1.9.0\direct\interval\FunctionInterval.py", line 88, in privInstant
    self.function(*self.extraArgs, **self.kw)
AssertionError: !is_empty() at line 1979 of c:\users\bryson\panda3d\panda\src\pgraph\nodePath.I
Traceback (most recent call last):
  File "otp\otpbase\OTPBase.py", line 239, in run
    taskMgr.run()
  File "C:\Panda3D-1.9.0\direct\task\Task.py", line 502, in run
    self.step()
  File "C:\Panda3D-1.9.0\direct\task\Task.py", line 460, in step
    self.mgr.poll()
  File "C:\Panda3D-1.9.0\direct\showbase\ShowBase.py", line 1801, in __ivalLoop
    IntervalManager.ivalMgr.step()
  File "C:\Panda3D-1.9.0\direct\interval\IntervalManager.py", line 96, in step
    self.__doPythonCallbacks()
  File "C:\Panda3D-1.9.0\direct\interval\IntervalManager.py", line 119, in __doPythonCallbacks
    ival.privPostEvent()
  File "C:\Panda3D-1.9.0\direct\interval\MetaInterval.py", line 518, in privPostEvent
    self.__doPythonCallbacks()
  File "C:\Panda3D-1.9.0\direct\interval\MetaInterval.py", line 494, in __doPythonCallbacks
    ival.privDoEvent(t, eventType)
  File "C:\Panda3D-1.9.0\direct\interval\Interval.py", line 207, in privDoEvent
    self.privInstant()
  File "C:\Panda3D-1.9.0\direct\interval\FunctionInterval.py", line 88, in privInstant
    self.function(*self.extraArgs, **self.kw)
AssertionError: !is_empty() at line 1979 of c:\users\bryson\panda3d\panda\src\pgraph\nodePath.I
